"""empty message

Revision ID: 7da10d7cdfee
Revises: None
Create Date: 2016-01-25 23:44:38.874063

"""

# revision identifiers, used by Alembic.
revision = '7da10d7cdfee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('match_name', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('users',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('user_alias', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('match_row',
    sa.Column('match_row_id', sa.Integer(), nullable=False),
    sa.Column('visitor', sa.Integer(), nullable=True),
    sa.Column('visitor_status', sa.Boolean(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ),
    sa.PrimaryKeyConstraint('match_row_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_row')
    op.drop_table('users')
    op.drop_table('match')
    ### end Alembic commands ###
